export const icons: { [key: string]: string } = {
    arcade:     "https://portalmod.net/emojis/arcade.png",
    booster:    "https://portalmod.net/emojis/booster.png",
    counting:   "https://portalmod.net/emojis/counting.png",
    events:     "https://portalmod.net/emojis/events.png",
    fire:       "https://portalmod.net/emojis/fire.png",
    glados:     "https://portalmod.net/emojis/glados.png",
    home:       "https://portalmod.net/emojis/home.png",
    important:  "https://portalmod.net/emojis/important.png",
    like:       "https://portalmod.net/emojis/like.png",
    mark:       "https://portalmod.net/emojis/mark.png",
    playtester: "https://portalmod.net/emojis/playtester.png",
    portalmod:  "https://portalmod.net/emojis/portalmod.png",
    supporter:  "https://portalmod.net/emojis/supporter.png",
    translate:  "https://portalmod.net/emojis/translate.png",
}